name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Reset & pull latest changes
        run: |
          cd /var/www/kimhoanjewelry/
          git reset --hard HEAD
          git clean -fd
          git pull origin main

      - name: Reload Apache
        run: |
          sudo /usr/bin/systemctl restart apache2.service
